// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GetBestBlockResponse
	Proof
	GetBlockRequest
	GetBlockResponse
	GetBlockHeaderRequest
	GetBlockHeaderResponse
	GetBlockVerboseRequest
	GetBlockVerboseV0Response
	GetBlockVerboseV1Response
	Tx
	Evidence
*/
package api

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetBestBlockResponse struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash   string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GetBestBlockResponse) Reset()                    { *m = GetBestBlockResponse{} }
func (m *GetBestBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBestBlockResponse) ProtoMessage()               {}
func (*GetBestBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

func (m *GetBestBlockResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetBestBlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Proof struct {
	Target uint64 `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Nonce  uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *Proof) Reset()                    { *m = Proof{} }
func (m *Proof) String() string            { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()               {}
func (*Proof) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{1} }

func (m *Proof) GetTarget() uint64 {
	if m != nil {
		return m.Target
	}
	return 0
}

func (m *Proof) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type GetBlockRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *GetBlockRequest) Reset()                    { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()               {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{2} }

func (m *GetBlockRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBlockResponse struct {
	Hash            string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ChainId         string   `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Version         uint64   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Height          uint64   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp       uint64   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Previous        string   `protobuf:"bytes,6,opt,name=previous,proto3" json:"previous,omitempty"`
	TransactionRoot string   `protobuf:"bytes,7,opt,name=transaction_root,json=transactionRoot,proto3" json:"transaction_root,omitempty"`
	WitnessRoot     string   `protobuf:"bytes,8,opt,name=witness_root,json=witnessRoot,proto3" json:"witness_root,omitempty"`
	Proof           *Proof   `protobuf:"bytes,9,opt,name=proof" json:"proof,omitempty"`
	Transactions    []string `protobuf:"bytes,10,rep,name=transactions" json:"transactions,omitempty"`
	Evidences       []string `protobuf:"bytes,11,rep,name=evidences" json:"evidences,omitempty"`
}

func (m *GetBlockResponse) Reset()                    { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()               {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{3} }

func (m *GetBlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *GetBlockResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetBlockResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetBlockResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetBlockResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetBlockResponse) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *GetBlockResponse) GetTransactionRoot() string {
	if m != nil {
		return m.TransactionRoot
	}
	return ""
}

func (m *GetBlockResponse) GetWitnessRoot() string {
	if m != nil {
		return m.WitnessRoot
	}
	return ""
}

func (m *GetBlockResponse) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *GetBlockResponse) GetTransactions() []string {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *GetBlockResponse) GetEvidences() []string {
	if m != nil {
		return m.Evidences
	}
	return nil
}

type GetBlockHeaderRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *GetBlockHeaderRequest) Reset()                    { *m = GetBlockHeaderRequest{} }
func (m *GetBlockHeaderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockHeaderRequest) ProtoMessage()               {}
func (*GetBlockHeaderRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{4} }

func (m *GetBlockHeaderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBlockHeaderResponse struct {
	Hash            string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ChainId         string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Version         uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Height          uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp       uint64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Previous        string `protobuf:"bytes,6,opt,name=previous,proto3" json:"previous,omitempty"`
	TransactionRoot string `protobuf:"bytes,7,opt,name=transaction_root,json=transactionRoot,proto3" json:"transaction_root,omitempty"`
	WitnessRoot     string `protobuf:"bytes,8,opt,name=witness_root,json=witnessRoot,proto3" json:"witness_root,omitempty"`
	Proof           *Proof `protobuf:"bytes,9,opt,name=proof" json:"proof,omitempty"`
}

func (m *GetBlockHeaderResponse) Reset()                    { *m = GetBlockHeaderResponse{} }
func (m *GetBlockHeaderResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockHeaderResponse) ProtoMessage()               {}
func (*GetBlockHeaderResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{5} }

func (m *GetBlockHeaderResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *GetBlockHeaderResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetBlockHeaderResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetBlockHeaderResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetBlockHeaderResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetBlockHeaderResponse) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *GetBlockHeaderResponse) GetTransactionRoot() string {
	if m != nil {
		return m.TransactionRoot
	}
	return ""
}

func (m *GetBlockHeaderResponse) GetWitnessRoot() string {
	if m != nil {
		return m.WitnessRoot
	}
	return ""
}

func (m *GetBlockHeaderResponse) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type GetBlockVerboseRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *GetBlockVerboseRequest) Reset()                    { *m = GetBlockVerboseRequest{} }
func (m *GetBlockVerboseRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockVerboseRequest) ProtoMessage()               {}
func (*GetBlockVerboseRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{6} }

func (m *GetBlockVerboseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBlockVerboseV0Response struct {
	Hash            string                                   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ChainId         string                                   `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Version         uint64                                   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Height          uint64                                   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp       uint64                                   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Previous        string                                   `protobuf:"bytes,6,opt,name=previous,proto3" json:"previous,omitempty"`
	TransactionRoot string                                   `protobuf:"bytes,7,opt,name=transaction_root,json=transactionRoot,proto3" json:"transaction_root,omitempty"`
	WitnessRoot     string                                   `protobuf:"bytes,8,opt,name=witness_root,json=witnessRoot,proto3" json:"witness_root,omitempty"`
	Proof           *Proof                                   `protobuf:"bytes,9,opt,name=proof" json:"proof,omitempty"`
	Transactions    []*GetBlockVerboseV0Response_Transaction `protobuf:"bytes,10,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *GetBlockVerboseV0Response) Reset()                    { *m = GetBlockVerboseV0Response{} }
func (m *GetBlockVerboseV0Response) String() string            { return proto.CompactTextString(m) }
func (*GetBlockVerboseV0Response) ProtoMessage()               {}
func (*GetBlockVerboseV0Response) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{7} }

func (m *GetBlockVerboseV0Response) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *GetBlockVerboseV0Response) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetBlockVerboseV0Response) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetBlockVerboseV0Response) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetBlockVerboseV0Response) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetBlockVerboseV0Response) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *GetBlockVerboseV0Response) GetTransactionRoot() string {
	if m != nil {
		return m.TransactionRoot
	}
	return ""
}

func (m *GetBlockVerboseV0Response) GetWitnessRoot() string {
	if m != nil {
		return m.WitnessRoot
	}
	return ""
}

func (m *GetBlockVerboseV0Response) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *GetBlockVerboseV0Response) GetTransactions() []*GetBlockVerboseV0Response_Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetBlockVerboseV0Response_Transaction struct {
	Txid      string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Evidences []string `protobuf:"bytes,2,rep,name=evidences" json:"evidences,omitempty"`
}

func (m *GetBlockVerboseV0Response_Transaction) Reset()         { *m = GetBlockVerboseV0Response_Transaction{} }
func (m *GetBlockVerboseV0Response_Transaction) String() string { return proto.CompactTextString(m) }
func (*GetBlockVerboseV0Response_Transaction) ProtoMessage()    {}
func (*GetBlockVerboseV0Response_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptorApi, []int{7, 0}
}

func (m *GetBlockVerboseV0Response_Transaction) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *GetBlockVerboseV0Response_Transaction) GetEvidences() []string {
	if m != nil {
		return m.Evidences
	}
	return nil
}

type GetBlockVerboseV1Response struct {
	Hash            string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ChainId         string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Version         uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Height          uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp       uint64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Previous        string `protobuf:"bytes,6,opt,name=previous,proto3" json:"previous,omitempty"`
	TransactionRoot string `protobuf:"bytes,7,opt,name=transaction_root,json=transactionRoot,proto3" json:"transaction_root,omitempty"`
	WitnessRoot     string `protobuf:"bytes,8,opt,name=witness_root,json=witnessRoot,proto3" json:"witness_root,omitempty"`
	Proof           *Proof `protobuf:"bytes,9,opt,name=proof" json:"proof,omitempty"`
	Transactions    []*Tx  `protobuf:"bytes,10,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *GetBlockVerboseV1Response) Reset()                    { *m = GetBlockVerboseV1Response{} }
func (m *GetBlockVerboseV1Response) String() string            { return proto.CompactTextString(m) }
func (*GetBlockVerboseV1Response) ProtoMessage()               {}
func (*GetBlockVerboseV1Response) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{8} }

func (m *GetBlockVerboseV1Response) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *GetBlockVerboseV1Response) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetBlockVerboseV1Response) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetBlockVerboseV1Response) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetBlockVerboseV1Response) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetBlockVerboseV1Response) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *GetBlockVerboseV1Response) GetTransactionRoot() string {
	if m != nil {
		return m.TransactionRoot
	}
	return ""
}

func (m *GetBlockVerboseV1Response) GetWitnessRoot() string {
	if m != nil {
		return m.WitnessRoot
	}
	return ""
}

func (m *GetBlockVerboseV1Response) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *GetBlockVerboseV1Response) GetTransactions() []*Tx {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Tx struct {
	Txid      string      `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Version   uint64      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Inputs    []*Tx_TxIn  `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	Outputs   []*Tx_TxOut `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
	Evidences []*Evidence `protobuf:"bytes,5,rep,name=evidences" json:"evidences,omitempty"`
	LockTime  uint64      `protobuf:"varint,6,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{9} }

func (m *Tx) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Tx) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Tx) GetInputs() []*Tx_TxIn {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Tx) GetOutputs() []*Tx_TxOut {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Tx) GetEvidences() []*Evidence {
	if m != nil {
		return m.Evidences
	}
	return nil
}

func (m *Tx) GetLockTime() uint64 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

type Tx_TxIn struct {
	ValueSource  *Tx_TxIn_ValueSource `protobuf:"bytes,1,opt,name=value_source,json=valueSource" json:"value_source,omitempty"`
	RedeemScript string               `protobuf:"bytes,2,opt,name=redeem_script,json=redeemScript,proto3" json:"redeem_script,omitempty"`
	UnlockScript string               `protobuf:"bytes,3,opt,name=unlock_script,json=unlockScript,proto3" json:"unlock_script,omitempty"`
	Sequence     uint64               `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *Tx_TxIn) Reset()                    { *m = Tx_TxIn{} }
func (m *Tx_TxIn) String() string            { return proto.CompactTextString(m) }
func (*Tx_TxIn) ProtoMessage()               {}
func (*Tx_TxIn) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{9, 0} }

func (m *Tx_TxIn) GetValueSource() *Tx_TxIn_ValueSource {
	if m != nil {
		return m.ValueSource
	}
	return nil
}

func (m *Tx_TxIn) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *Tx_TxIn) GetUnlockScript() string {
	if m != nil {
		return m.UnlockScript
	}
	return ""
}

func (m *Tx_TxIn) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type Tx_TxIn_ValueSource struct {
	Txid  string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *Tx_TxIn_ValueSource) Reset()                    { *m = Tx_TxIn_ValueSource{} }
func (m *Tx_TxIn_ValueSource) String() string            { return proto.CompactTextString(m) }
func (*Tx_TxIn_ValueSource) ProtoMessage()               {}
func (*Tx_TxIn_ValueSource) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{9, 0, 0} }

func (m *Tx_TxIn_ValueSource) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Tx_TxIn_ValueSource) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Tx_TxOut struct {
	Value      uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	ScriptHash string `protobuf:"bytes,2,opt,name=script_hash,json=scriptHash,proto3" json:"script_hash,omitempty"`
}

func (m *Tx_TxOut) Reset()                    { *m = Tx_TxOut{} }
func (m *Tx_TxOut) String() string            { return proto.CompactTextString(m) }
func (*Tx_TxOut) ProtoMessage()               {}
func (*Tx_TxOut) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{9, 1} }

func (m *Tx_TxOut) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Tx_TxOut) GetScriptHash() string {
	if m != nil {
		return m.ScriptHash
	}
	return ""
}

type Evidence struct {
	Evid        string `protobuf:"bytes,1,opt,name=evid,proto3" json:"evid,omitempty"`
	Digest      string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Source      string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	ValidScript string `protobuf:"bytes,4,opt,name=valid_script,json=validScript,proto3" json:"valid_script,omitempty"`
}

func (m *Evidence) Reset()                    { *m = Evidence{} }
func (m *Evidence) String() string            { return proto.CompactTextString(m) }
func (*Evidence) ProtoMessage()               {}
func (*Evidence) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{10} }

func (m *Evidence) GetEvid() string {
	if m != nil {
		return m.Evid
	}
	return ""
}

func (m *Evidence) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Evidence) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Evidence) GetValidScript() string {
	if m != nil {
		return m.ValidScript
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBestBlockResponse)(nil), "api.GetBestBlockResponse")
	proto.RegisterType((*Proof)(nil), "api.Proof")
	proto.RegisterType((*GetBlockRequest)(nil), "api.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "api.GetBlockResponse")
	proto.RegisterType((*GetBlockHeaderRequest)(nil), "api.GetBlockHeaderRequest")
	proto.RegisterType((*GetBlockHeaderResponse)(nil), "api.GetBlockHeaderResponse")
	proto.RegisterType((*GetBlockVerboseRequest)(nil), "api.GetBlockVerboseRequest")
	proto.RegisterType((*GetBlockVerboseV0Response)(nil), "api.GetBlockVerboseV0Response")
	proto.RegisterType((*GetBlockVerboseV0Response_Transaction)(nil), "api.GetBlockVerboseV0Response.Transaction")
	proto.RegisterType((*GetBlockVerboseV1Response)(nil), "api.GetBlockVerboseV1Response")
	proto.RegisterType((*Tx)(nil), "api.Tx")
	proto.RegisterType((*Tx_TxIn)(nil), "api.Tx.TxIn")
	proto.RegisterType((*Tx_TxIn_ValueSource)(nil), "api.Tx.TxIn.ValueSource")
	proto.RegisterType((*Tx_TxOut)(nil), "api.Tx.TxOut")
	proto.RegisterType((*Evidence)(nil), "api.Evidence")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for APIService service

type APIServiceClient interface {
	GetBestBlock(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetBestBlockResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	GetBlockHeader(ctx context.Context, in *GetBlockHeaderRequest, opts ...grpc.CallOption) (*GetBlockHeaderResponse, error)
	GetBlockVerboseV0(ctx context.Context, in *GetBlockVerboseRequest, opts ...grpc.CallOption) (*GetBlockVerboseV0Response, error)
	GetBlockVerboseV1(ctx context.Context, in *GetBlockVerboseRequest, opts ...grpc.CallOption) (*GetBlockVerboseV1Response, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) GetBestBlock(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetBestBlockResponse, error) {
	out := new(GetBestBlockResponse)
	err := grpc.Invoke(ctx, "/api.APIService/GetBestBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := grpc.Invoke(ctx, "/api.APIService/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBlockHeader(ctx context.Context, in *GetBlockHeaderRequest, opts ...grpc.CallOption) (*GetBlockHeaderResponse, error) {
	out := new(GetBlockHeaderResponse)
	err := grpc.Invoke(ctx, "/api.APIService/GetBlockHeader", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBlockVerboseV0(ctx context.Context, in *GetBlockVerboseRequest, opts ...grpc.CallOption) (*GetBlockVerboseV0Response, error) {
	out := new(GetBlockVerboseV0Response)
	err := grpc.Invoke(ctx, "/api.APIService/GetBlockVerboseV0", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBlockVerboseV1(ctx context.Context, in *GetBlockVerboseRequest, opts ...grpc.CallOption) (*GetBlockVerboseV1Response, error) {
	out := new(GetBlockVerboseV1Response)
	err := grpc.Invoke(ctx, "/api.APIService/GetBlockVerboseV1", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for APIService service

type APIServiceServer interface {
	GetBestBlock(context.Context, *google_protobuf1.Empty) (*GetBestBlockResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	GetBlockHeader(context.Context, *GetBlockHeaderRequest) (*GetBlockHeaderResponse, error)
	GetBlockVerboseV0(context.Context, *GetBlockVerboseRequest) (*GetBlockVerboseV0Response, error)
	GetBlockVerboseV1(context.Context, *GetBlockVerboseRequest) (*GetBlockVerboseV1Response, error)
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_GetBestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBestBlock(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBlockHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBlockHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBlockHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBlockHeader(ctx, req.(*GetBlockHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBlockVerboseV0_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockVerboseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBlockVerboseV0(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBlockVerboseV0",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBlockVerboseV0(ctx, req.(*GetBlockVerboseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBlockVerboseV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockVerboseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBlockVerboseV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBlockVerboseV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBlockVerboseV1(ctx, req.(*GetBlockVerboseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBestBlock",
			Handler:    _APIService_GetBestBlock_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _APIService_GetBlock_Handler,
		},
		{
			MethodName: "GetBlockHeader",
			Handler:    _APIService_GetBlockHeader_Handler,
		},
		{
			MethodName: "GetBlockVerboseV0",
			Handler:    _APIService_GetBlockVerboseV0_Handler,
		},
		{
			MethodName: "GetBlockVerboseV1",
			Handler:    _APIService_GetBlockVerboseV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptorApi) }

var fileDescriptorApi = []byte{
	// 896 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x56, 0x1c, 0xa7, 0x49, 0x8e, 0xb3, 0xdb, 0xdd, 0x51, 0xb7, 0xb8, 0xce, 0x6a, 0x49, 0x0d,
	0xd2, 0x06, 0x56, 0xb2, 0x37, 0x45, 0x88, 0x0b, 0x24, 0x10, 0x95, 0x56, 0x6c, 0x6f, 0xa0, 0x72,
	0xa3, 0x5e, 0x70, 0x13, 0x39, 0xf6, 0x6c, 0x32, 0xa2, 0xf1, 0x78, 0x3d, 0x63, 0x13, 0x84, 0xb8,
	0xe1, 0x05, 0xb8, 0xe0, 0x11, 0x78, 0x08, 0x1e, 0x64, 0x1f, 0x00, 0x09, 0xf1, 0x00, 0x3c, 0x02,
	0x9a, 0x1f, 0x27, 0xb6, 0x93, 0x56, 0x88, 0xeb, 0xde, 0xf9, 0x9c, 0xf3, 0xcd, 0x7c, 0x67, 0xbe,
	0x6f, 0x3c, 0x33, 0xd0, 0x0f, 0x53, 0xe2, 0xa5, 0x19, 0xe5, 0x14, 0xb5, 0xc3, 0x94, 0x38, 0x4f,
	0x17, 0x94, 0x2e, 0x6e, 0xb0, 0x1f, 0xa6, 0xc4, 0x0f, 0x93, 0x84, 0xf2, 0x90, 0x13, 0x9a, 0x30,
	0x05, 0x71, 0x86, 0xba, 0x2a, 0xa3, 0x79, 0xfe, 0xc6, 0xc7, 0xab, 0x94, 0xff, 0xa8, 0x8a, 0xee,
	0x39, 0x1c, 0x7d, 0x8d, 0xf9, 0x39, 0x66, 0xfc, 0xfc, 0x86, 0x46, 0xdf, 0x07, 0x98, 0xa5, 0x34,
	0x61, 0x18, 0x1d, 0xc3, 0xc1, 0x12, 0x93, 0xc5, 0x92, 0xdb, 0xad, 0x51, 0x6b, 0x6c, 0x06, 0x3a,
	0x42, 0x08, 0xcc, 0x65, 0xc8, 0x96, 0xb6, 0x31, 0x6a, 0x8d, 0xfb, 0x81, 0xfc, 0x76, 0x3f, 0x85,
	0xce, 0x65, 0x46, 0xe9, 0x1b, 0x31, 0x88, 0x87, 0xd9, 0x02, 0x6f, 0x06, 0xa9, 0x08, 0x1d, 0x41,
	0x27, 0xa1, 0x49, 0x84, 0xe5, 0x28, 0x33, 0x50, 0x81, 0x7b, 0x0a, 0x87, 0x82, 0x5a, 0xd1, 0xbe,
	0xcd, 0x31, 0xe3, 0xe8, 0x21, 0x18, 0x24, 0x96, 0x83, 0xfb, 0x81, 0x41, 0x62, 0xf7, 0x4f, 0x03,
	0x1e, 0x6d, 0x31, 0xba, 0xb5, 0xb2, 0x85, 0xd6, 0xb6, 0x05, 0x74, 0x02, 0xbd, 0x68, 0x19, 0x92,
	0x64, 0x46, 0x62, 0xdd, 0x5a, 0x57, 0xc6, 0x17, 0x31, 0xb2, 0xa1, 0x5b, 0xe0, 0x8c, 0x11, 0x9a,
	0xd8, 0x6d, 0x49, 0x5f, 0x86, 0x95, 0x35, 0x9a, 0xb5, 0x35, 0x3e, 0x85, 0x3e, 0x27, 0x2b, 0xcc,
	0x78, 0xb8, 0x4a, 0xed, 0x8e, 0x2c, 0x6d, 0x13, 0xc8, 0x81, 0x5e, 0x9a, 0xe1, 0x82, 0xd0, 0x9c,
	0xd9, 0x07, 0x92, 0x6a, 0x13, 0xa3, 0x8f, 0xe0, 0x11, 0xcf, 0xc2, 0x84, 0x85, 0x91, 0x30, 0x60,
	0x96, 0x51, 0xca, 0xed, 0xae, 0xc4, 0x1c, 0x56, 0xf2, 0x01, 0xa5, 0x1c, 0x9d, 0xc2, 0xe0, 0x07,
	0xc2, 0x13, 0xcc, 0x98, 0x82, 0xf5, 0x24, 0xcc, 0xd2, 0x39, 0x09, 0x19, 0x41, 0x27, 0x15, 0xba,
	0xda, 0xfd, 0x51, 0x6b, 0x6c, 0x9d, 0x81, 0x27, 0x6c, 0x97, 0x4a, 0x07, 0xaa, 0x80, 0x5c, 0x18,
	0x54, 0xe6, 0x65, 0x36, 0x8c, 0xda, 0xe3, 0x7e, 0x50, 0xcb, 0x89, 0xd5, 0xe0, 0x82, 0xc4, 0x38,
	0x89, 0x30, 0xb3, 0x2d, 0x09, 0xd8, 0x26, 0xdc, 0xe7, 0xf0, 0xa4, 0x14, 0xf8, 0x35, 0x0e, 0x63,
	0x9c, 0xdd, 0x66, 0xc5, 0xef, 0x06, 0x1c, 0x37, 0x91, 0xf7, 0x86, 0x34, 0x0c, 0x71, 0xc7, 0x5b,
	0x91, 0xae, 0x71, 0x36, 0xa7, 0x0c, 0xdf, 0xa6, 0xe7, 0x1f, 0x6d, 0x38, 0x69, 0x40, 0xaf, 0x5f,
	0xde, 0x4b, 0xba, 0xbb, 0xc7, 0xbf, 0xd9, 0xb3, 0xc7, 0xad, 0xb3, 0x8f, 0x25, 0xf0, 0x56, 0x01,
	0xbd, 0x69, 0xa5, 0x95, 0xda, 0x78, 0xe7, 0x4b, 0xb0, 0x2a, 0x45, 0xa1, 0x34, 0x5f, 0x6f, 0x9c,
	0x91, 0xdf, 0xf5, 0x5f, 0xc6, 0x68, 0xfe, 0x32, 0xef, 0x8c, 0x5d, 0xe7, 0x26, 0xf7, 0xce, 0xed,
	0x3a, 0xf7, 0x62, 0xaf, 0x73, 0x5d, 0x09, 0x9c, 0xae, 0xeb, 0xb6, 0xb8, 0xff, 0xb4, 0xc1, 0x98,
	0xae, 0xf7, 0xda, 0x51, 0xd1, 0xc8, 0xa8, 0x6b, 0xf4, 0x21, 0x1c, 0x90, 0x24, 0xcd, 0x39, 0xb3,
	0xdb, 0x72, 0xee, 0x81, 0x9e, 0xdb, 0x9b, 0xae, 0x2f, 0x92, 0x40, 0xd7, 0xd0, 0x73, 0xe8, 0xd2,
	0x9c, 0x4b, 0x98, 0x29, 0x61, 0x0f, 0xb6, 0xb0, 0x6f, 0x73, 0x1e, 0x94, 0x55, 0xf4, 0xa2, 0xea,
	0x7b, 0xa7, 0x02, 0x7d, 0xa5, 0xb3, 0x95, 0x6d, 0x80, 0x86, 0xd0, 0x17, 0x3b, 0x60, 0x26, 0xb4,
	0x97, 0x52, 0x9b, 0x41, 0x4f, 0x24, 0xa6, 0x64, 0x85, 0x9d, 0xbf, 0x5a, 0x60, 0x8a, 0x1e, 0xd0,
	0xe7, 0x30, 0x28, 0xc2, 0x9b, 0x1c, 0xcf, 0x18, 0xcd, 0xb3, 0x08, 0xcb, 0x75, 0x59, 0x67, 0x76,
	0xb5, 0x4f, 0xef, 0x5a, 0x00, 0xae, 0x64, 0x3d, 0xb0, 0x8a, 0x6d, 0x80, 0x3e, 0x80, 0x07, 0x19,
	0x8e, 0x31, 0x5e, 0xcd, 0x58, 0x94, 0x91, 0x94, 0xeb, 0xcd, 0x33, 0x50, 0xc9, 0x2b, 0x99, 0x13,
	0xa0, 0x3c, 0x91, 0x9d, 0x68, 0x50, 0x5b, 0x81, 0x54, 0x52, 0x83, 0x1c, 0xe8, 0x31, 0x71, 0x10,
	0x89, 0x4b, 0x58, 0x6d, 0xa7, 0x4d, 0xec, 0x7c, 0x06, 0x56, 0xa5, 0x83, 0xbd, 0x0e, 0x1c, 0x41,
	0x87, 0x24, 0x31, 0x5e, 0x97, 0x17, 0xb8, 0x0c, 0x9c, 0x2f, 0xa0, 0x23, 0x05, 0x14, 0x65, 0xd9,
	0xb6, 0xbe, 0xf6, 0x55, 0x80, 0xde, 0x07, 0x4b, 0x75, 0x34, 0xab, 0xbc, 0x18, 0x40, 0xa5, 0x5e,
	0x8b, 0x77, 0xc3, 0x5b, 0xe8, 0x95, 0xc2, 0x0a, 0x56, 0x21, 0x6d, 0xc9, 0x2a, 0xbe, 0xc5, 0x1f,
	0x10, 0x93, 0x05, 0x66, 0xe5, 0xba, 0x75, 0x24, 0xf2, 0x5a, 0x4d, 0xb5, 0x54, 0x1d, 0x89, 0x4d,
	0x5b, 0x84, 0x37, 0x24, 0x2e, 0x85, 0x30, 0xd5, 0xa6, 0x95, 0x39, 0xa5, 0xc3, 0xd9, 0xaf, 0x26,
	0xc0, 0x57, 0x97, 0x17, 0x57, 0x38, 0x2b, 0x48, 0x84, 0xd1, 0x77, 0x30, 0xa8, 0xbe, 0x7e, 0xd0,
	0xb1, 0xa7, 0xde, 0x4a, 0x5e, 0xf9, 0x56, 0xf2, 0x5e, 0x89, 0xb7, 0x92, 0x73, 0xb2, 0x39, 0x6d,
	0x9a, 0x0f, 0x25, 0xf7, 0xbd, 0x5f, 0xde, 0xfd, 0xfd, 0x9b, 0xf1, 0x18, 0x1d, 0xfa, 0xc5, 0xc4,
	0x9f, 0x8b, 0x12, 0xf3, 0xe7, 0xa2, 0xcb, 0x4b, 0xe8, 0x95, 0xa7, 0x04, 0x3a, 0xaa, 0x9d, 0x56,
	0xfa, 0x4a, 0x70, 0x9e, 0x34, 0xb2, 0x77, 0xcc, 0xf8, 0x13, 0x89, 0x7f, 0x46, 0x04, 0x1e, 0xd6,
	0x6f, 0x60, 0xe4, 0xd4, 0x66, 0xa8, 0x5d, 0xe0, 0xce, 0x70, 0x6f, 0x4d, 0x73, 0x3c, 0x93, 0x1c,
	0x36, 0x3a, 0x6e, 0x70, 0xf8, 0x4b, 0x35, 0x31, 0x83, 0xc7, 0x3b, 0x67, 0x2b, 0x1a, 0xee, 0x3b,
	0x73, 0x4b, 0xba, 0x67, 0x77, 0x1f, 0xc8, 0xee, 0xa9, 0x64, 0x1c, 0xa2, 0x93, 0x26, 0x63, 0xa1,
	0xa0, 0xfe, 0xcb, 0x7d, 0xa4, 0x93, 0xff, 0x43, 0x3a, 0xf9, 0xef, 0xa4, 0x93, 0xf9, 0x81, 0xb4,
	0xfa, 0x93, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xc7, 0x12, 0x68, 0x54, 0x0b, 0x00, 0x00,
}
